#!/usr/bin/env php
<?php

use Pangaea\ConsoleCommands\Console\Console;
use Pangaea\ConsoleCommands\Console\Input;

require __DIR__.'/vendor/autoload.php';

$console = new Console(new Input());

$status = $console->handle();

$console->terminate($status);